services:
  dod-soutez:
    build:
      context: .
      args:
        - VITE_TURNSTILE_SITEKEY=${VITE_TURNSTILE_SITEKEY}
    container_name: dod-soutez-app
    # Port 5173 uvnitř kontejneru
    ports:
      - "5173:5173"
    networks:
      - cloudflare_net
    restart: always

networks:
  cloudflare_net:
    external: true # Předpokládá, že síť vytvoříte nebo ji sdílíte s tunelem
